[package]
name = "oop"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
TreeComposite = {path = "lib/TreeComposite"}
RGBMixer = {path = "lib/RGBMixer"}